### ISSUE TITLE
Simulating filtered noise breaks when n_seconds is too small

### ISSUE THREAD

**Issue by srcole** [neurodsp-tools/neurodsp#115]
`sim_filtered_noise()` breaks for some simulations that users may want to run and doesn't give a particularly helpful error. We can change the code to get past this error.

Basically, if the signal is not 3x longer than the filter, then an error occurs, e.g.
```python
n_seconds = 10
fs = 1000
exponent = -2
sim_filtered_noise(n_seconds, fs, exponent, f_range=(2, None), filter_order=5001)
```
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-584a47fbfc12> in <module>()
      2 fs = 1000
      3 exponent = -2
----> 4 sim_filtered_noise(n_seconds, fs, exponent, f_range=(2, None), filter_order=5001)

/gh/bv/neurodsp/neurodsp/sim.py in sim_filtered_noise(n_seconds, fs, exponent, f_range, filter_order)
    794         # High pass filter
    795         taps = signal.firwin(filter_order, f_range[0] / nyq, pass_zero=False)
--> 796         noise = signal.filtfilt(taps, [1], noise)
    797 
    798     # Band pass filtered

~/anaconda/lib/python3.6/site-packages/scipy/signal/signaltools.py in filtfilt(b, a, x, axis, padtype, padlen, method, irlen)
   3097     # method == "pad"
   3098     edge, ext = _validate_pad(padtype, padlen, x, axis,
-> 3099                               ntaps=max(len(a), len(b)))
   3100 
   3101     # Get the steady state of the filter's step response.

~/anaconda/lib/python3.6/site-packages/scipy/signal/signaltools.py in _validate_pad(padtype, padlen, x, axis, ntaps)
   3147     if x.shape[axis] <= edge:
   3148         raise ValueError("The length of the input vector x must be at least "
-> 3149                          "padlen, which is %d." % edge)
   3150 
   3151     if padtype is not None and edge > 0:

ValueError: The length of the input vector x must be at least padlen, which is 15003.
```

The signal is 10,000 samples long (`n_seconds` * `fs`), and `scipy.signal.filtfilt()` seems to require at least 3 times the length of the filter (5,001 samples, in this case).

One issue. Is that we should not be using `filtfilt`. We should be using our own highpass/bandpass filter functionality that uses one-pass filtering, to be consistent.

We also need to deal with edge artifacts of the filter. To simulate 10 seconds of a signal that has a highpass filter of 3 seconds, we should simulate 16 seconds, and then chop off the edge artifacts.

**Comment by rdgao** [comment]
So sim_filtered_noise should ALWAYS be simulating more signal than required by n_seconds, since the filtering introduces edge artifacts that should be thrown out regardless of length, right?

I don't necessarily disagree with that since that's the natural thing to do, but just throwing out some ideas: what about something a little more sophisticated, because simulating that much signal and then throwing it away seems kinda inefficient/ an overkill. 

The entire reason for sim_filtered_noise's existence is that variable_powerlaw with large exponents produce signals with really bad drifts. So what if we just remove linear or quadratic trends with spline fitting? Or literally just use sp.signal.detrend?

**Comment by TomDonoghue** [comment]
Are the 'really bad drifts' different than just reflecting that there is the desired power law, with lots of power in low frequencies? (As in those drifts are, in some sense, accurate right)?

The 'drifts', are a different problem then a signal 'offset', right, as was brought up in #119, and updated with #126. (Related to that - why do we demean noise in the combined funcs, and not just generally demean the signal in the generate_noise functions?). 

Or, another way to put: when simulating arbitrarily long signals, the 'drifts' reflect the desired 1/f property of the signal, right, reflecting the abundance of low frequency power? If one filters, one breaks that 1/f, but at least across some predictable range (below f_hi, if high passing). But if we update to start removing these trends, is it predictably to what extent one changes the 1/f nature of the signal? (As is, if I simulate a signal, where and to what extent have I messed with the desired 1/f nature of the signal by removing those slow trends?)

**Comment by rdgao** [comment]
that's a good point - the filter approach allows much better control of exponent across a specific frequency range of interest for all signal lengths, whereas constant or linear detrend will give you different frequency responses depending on the signal length

**Comment by TomDonoghue** [comment]
Okay - revisiting this.

It seems mostly outdated, at least in that:
- We decided to keep the filtering approach, and do now use internal filters
- We do now have better errors / notes on short filters. 

Some related changes:

CODE FIX:
When checking through this, I realized we had a silly bug that actually meant that trying to do filtering in `sim_powerlaw` didn't work, in the 2.0 update. Fixed now. 

CODE UPDATE:
Also, at default, the approach right now trims edges, and so includes NaNs in the output signal. 
So, I update sim_powerlaw to calculate the filter length and compensate for this. So now you can simulate filtered powerlaws and it will also compensate to give the desired length of the signal, without NaNs or edge artifacts included. Since this always extends the signal length beyond the filter length, it also has a nice side effect of avoiding the original issue here, where the filter length ends up longer than the signal. 

So I think this is all good now - and does what we want. I don't think there's anything else to do here, as most of this thread is out of date - but feel free to re-open (or, perhaps, open a new issue) with any thoughts / related notes.
