### ISSUE TITLE
Add a glossary?

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#138]
How do we feel about adding a glossary to the documentation site?
Example: https://fooof-tools.github.io/fooof/glossary.html

For example, when I was working through the filter refactor, I started keeping track of all the jargon terms that we don't really define (for example: passband, transition band, kernel, even just a note on what FIR & IIR are) and it seems like we could collect this list of terms, and add a glossary quickly and roughly defining them. 

The balance is that I think we don't want to consider it part of NDSP to create and maintain full tutorials for general DSP, so we might consider this out of scope - but I feel like we might be able to crowd-source a glossary fairly quickly in the lab, as a quick guide for people relatively new to the codebase. 

Alternatively, or in addition, if people know of some good external resources for the topics covered here, we can explicitly add links to them and outsource some of them. If anyone knows of a similar glossary to link to - that would be perfect. 

The question is for @voytek & @rdgao mostly, I guess.

**Comment by voytek** [comment]
>we don't want to consider it part of NDSP to create and maintain full tutorials for general DSP

Correct, though we're building toward that in a sense, anyway, as we build out our onboarding materials, so I see no reason not to allow ndsp to be a place for us (and the community and large?) to do that.

**Comment by rdgao** [comment]
So is the idea that it's all in one place here in `neurodsp` instead of having somebody Google/find all the terms themselves when they come across it? If so, can we get the next undergrads that use it to just jot down all the stuff they don't understand?

As a whole, I think this is a good idea, but I have one concern/suggestion: I think the glossary should be a collection of outgoing resources on what, e.g., an FIR filter is, instead of defining it ourselves. Because I don't think a one-pager glossary should be the go-to source for somebody to learn DSP, regardless of whether it's constrained to the context of neuro.

**Comment by TomDonoghue** [comment]
Totally agreed on linking to external resources! To be clear, I also wasn't thinking of the glossary including tutorial level details (definitely outsource that), but more a definition list. 

For the simplest example, one might have FIR in the glossary as (and including the idea of linking out):
```
FIR:
    A finite impulse response filter, meaning the response to an input of finite length is also finite. 
    For more information on FIR filters see: XXX
```

Right now the code itself doesn't even say expand what FIR stands for. And for other terms, like passband, transition band, I think a one sentence primer could do a lot. 

Also, yeh, I think getting UGs and other people working through the code to crowdsource this is the easiest way to develop it.
