### ISSUE TITLE
rhythm/lc.py lagged_coherence returning nan

### ISSUE THREAD

**Issue by samnemo** [neurodsp-tools/neurodsp#153]
lagged_coherence often returns nan for low frequency (delta, theta oscillations) coherence test, due to     return np.abs(lcs_num / lcs_denom), not checking lcs_denom != 0.0; the calling function will return nan if even a single lcs_denom==0.0, since it's using np.mean(lc). One fix is for the  calling function to use np.nanmean(lc) instead, that would avoid returning nan, but it wouldn't fix the source of the problem which is that lcs_denom can be 0 if the Fourier coefficients are 0.

**Comment by samnemo** [comment]
this problem is caused by having not enough samples n_samps = int(np.ceil(n_cycles * fs / freq)) and not enough chunks when using a low frequency compared to length of the input signal; maybe useful to provide a warning...

**Comment by TomDonoghue** [comment]
Hey @samnemo 

Sorry this response is ridiculously late! Somehow this issue slipped through the cracks. 

Thank you for the notes, you are totally correct, lagged coherence doesn't do well with the low frequencies. 

To at least better annotate this, I have added printed note in the function about Nans, if they are calculated, and mentions what happened / what to do.

I decided not to switch to a nanmean, for now at least, because my worry is that would return values that would be easy to mis-interpret as reflecting the lagged coherence across the input f_range (if one just skips or doesn't see the warning) but this would be the wrong interpretation / answer. It feels safer to leave it as a nan if the function fails to compute the full range. The warning will describe what is happening, and the recommendation would be to update the settings or frequency range to get a non-nan value. One could always return the full spectrum and nanmean from there if there was a use case that really needed to estimate the average lagged coherence, regardless of nan presence. 

If you have any other thoughts / suggestions, please let us know. Also, @rdgao or @srcole - any strong thoughts on this? Anyone think we should update to nanmean? Otherwise, I think this is covered, and we can close this issue.

**Comment by rdgao** [comment]
yeah, I think warning is the right way to go here. I like nanmean as much as the next guy in my own code, but for a library like this, I think spitting out a nanmean by default could create a lot of inconsistencies.

**Comment by TomDonoghue** [comment]
Okay, cool - thanks for the confirmation Richard!

@samnemo - if you have any other thoughts on this, please feel free to let us know / re-open this issue etc, but for now I'm going to close this, since I don't think there is any other clear ToDo item!
