### ISSUE TITLE
Error when band passing signal with a High Sample Rate 

### ISSUE THREAD

**Issue by Darilbii** [neurodsp-tools/neurodsp#160]
![Screen Shot 2019-05-21 at 7 31 22 PM](https://user-images.githubusercontent.com/13894524/58143363-73221080-7bff-11e9-9517-8d4e746d363c.png)
![Screen Shot 2019-05-21 at 7 30 21 PM](https://user-images.githubusercontent.com/13894524/58143364-73221080-7bff-11e9-9ca1-401c22c88328.png)

**Comment by TomDonoghue** [comment]
This is the same error as described in ByCycle, here:
https://github.com/bycycle-tools/bycycle/issues/34

and fixed here:
https://github.com/bycycle-tools/bycycle/pull/35

It's a problem with checking transition bands with high sampling rates, since by default scipy calculates the frequency response at a sparse set of samples. 

The same solution should work here. Will check and update if so.

**Comment by TomDonoghue** [comment]
Fixed - same approach as in ByCycle.
