### ISSUE TITLE
DSP neural network for neural DSP!

### ISSUE THREAD

**Issue by S6Regen** [neurodsp-tools/neurodsp#168]
You might like to experiment with fixed filter bank neural networks if you like DSP.
One thing I noticed is strong GAN like behavior if you train as an autoassociator and then just feed in arbitrary noise.

[https://github.com/S6Regen/Fixed-Filter-Bank-Neural-Networks](url)

**Comment by TomDonoghue** [comment]
Huh. Neural networks with filter banks, DSP, FFTs, etc sounds really interesting. 

That's outside of my area of expertise, and the scope of this package though. I've linked the repo out to our lab, in case anyone wants to explore it, but since there's not a question per se here, I'm going to close this issue. 

Best of luck with your project!
