### ISSUE TITLE
Test failures with numpy 1.18.0

### ISSUE THREAD

**Issue by Aniket-Pradhan** [neurodsp-tools/neurodsp#175]
Hello dev-team. Thanks for working on and providing neurodsp.

I am working with a group, NeuroFedora whose main purpose is to package and provide NeuroScience software for the Fedora operating system. You can read more about us [here](https://neuroblog.fedoraproject.org).

We just experienced some test failures with the numpy 1.18.0 library. The failing tests are:
`neurodsp/tests/test_spectral_power.py`
`neurodsp/tests/test_timefrequency_wavelets.py`

The main error I noticed is:

```
>           num = operator.index(num)
E           TypeError: 'numpy.float64' object cannot be interpreted as an integer
.venv/lib/python3.7/site-packages/numpy/core/function_base.py:117: TypeError

>       out = compute_wavelet_transform(tsig, FS, FREQS_ARR)

neurodsp/tests/test_timefrequency_wavelets.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
neurodsp/utils/decorators.py:53: in wrapper
    out = func(sig, *args, **kwargs)
neurodsp/timefrequency/wavelets.py:44: in compute_wavelet_transform
    mwt[:, ind] = convolve_wavelet(sig, fs, freq, n_cycle, scaling)
neurodsp/utils/decorators.py:53: in wrapper
    out = func(sig, *args, **kwargs)
neurodsp/timefrequency/wavelets.py:92: in convolve_wavelet
    morlet_f = morlet(wavelet_len, w=n_cycles, s=scaling)
.venv/lib/python3.7/site-packages/scipy/signal/wavelets.py:253: in morlet
    x = np.linspace(-s * 2 * np.pi, s * 2 * np.pi, M)
<__array_function__ internals>:6: in linspace
    ???
```

This might be an error with scipy and/or numpy. **[Here](https://paste.centos.org/view/55c001ef)** are the detailed logs for context.

I can try and dig into the issue more. I will reply if I get something.

**Comment by Aniket-Pradhan** [comment]
After a quick investigation, I found that the issue is with `scipy.signal.morlet`. According to the [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.morlet.html), the first param (`M`) should be an integer. 

However, `neurodsp/timefrequency/wavelets.py` passes it the variable `wavelet_len` which is a [float](https://github.com/neurodsp-tools/neurodsp/blob/master/neurodsp/timefrequency/wavelets.py#L92). If we typecast it to `int`, the tests pass successfully and there are no errors.

Now, the question is whether we should typecast it or not? I have no clue about wavelets (for now :P), and whether `wavelet_len` should be an `int` or not. But since the docs have mentioned to use an `int`, neurodsp should use `int` itself.

**Comment by TomDonoghue** [comment]
Hey @Aniket-Pradhan 

Thank you for the note! Short answer: Yes! That value in `wavelet_len`, that gets passed in as `M` can and should be typecast!

Longer Answer:
This was not failing for us, on a slightly older version of numpy. I had a check through, and the issue appears to be an update in `np.linspace` (which gets called by `scipy.signal.morlet`) whereby the `num` input, which should be an int, will now actually fail if it is not an int value. This wasn't yet failing on our end because this is only a warning in the slightly older version of numpy, but is now an error (as it should be).

Either way - that input should be an integer, and it was just some sloppiness on our part that it was not guaranteed to be so. This is now fixed, on the master branch, by adding a typecast to int, as you suggested. 

Thank you for catching this and opening the issue! If there is anything else, let me know! Otherwise, I think this should be covered and we can close this issue.

**Comment by Aniket-Pradhan** [comment]
Hey Tom!

> Either way - that input should be an integer, and it was just some sloppiness on our part that it was not guaranteed to be so. This is now fixed, on the master branch, by adding a typecast to int, as you suggested.

Thanks a lot for fixing this bug. I will update the package in the Fedora cloud by including this commit as a patch until a new release for neurodsp comes about. :D

> Thank you for catching this and opening the issue! If there is anything else, let me know! Otherwise, I think this should be covered and we can close this issue.

Yep, this is resolved and therefore I will close the issue as well. Thanks!
