### ISSUE TITLE
question : understanding the different parameters in detect_burst function

### ISSUE THREAD

**Issue by apoorva6262** [neurodsp-tools/neurodsp#268]
Hi,

I just wanted more clarification on the different functions in identifying bursts. I am comparing the tutorial on burst detection with the example written in MNE.  By using `detect_bursts_dual_threshold` , what is the difference in using f_range as a frequency bandfilter (eg. f_range(13,30)) vs f_range as peak power (eg. f_range=(peakpower-2,peakpower+2) ; as shown on the MNE example) in an already bandpass filtered signal of interest (eg. filtered at beta frequency before using detect_dual_burst_threshold) ? 

When you define `dual_thresh=(1,2)`, does 1 = the average signal magnitude and 2= is 3 sigma deviation ? correct? So a number below one will have a lot of "bursts" because it's below the average. So it is bound to +/-1 ? 

Also, in your API, you mention that `min_burst_duration` must be defined if NOT filtering. How does that work? I am just looking at some of the published papers on bursts and they mention that 50-100ms is the minimum burst duration required to be defined as a burst. 

Thanks.

**Comment by ryanhammonds** [comment]
Hi!

If your signal is already filtered to a range of interest, `f_range=None` (default) may be used to avoid a second filter. The MNE example shows that peak spectral power may be used if you don't know the frequency range where oscillations are likely to exists - a better way to do this would be using bandwidths from spectral parametrization (fooof).

`dual_thresh=(1, 2)` refers to the lower and upper amplitude thresholds (not mean and std). The starts of bursts are defined where the normalized amplitude of the signal is above `dual_thresh[1]`, and the burst ends when the normalized amplitude drops below `dual_thresh[0]`.

The min burst length is defined by default as 3 time the length of the lower frequency (`3 * fs / f_range[0]`), but only when f_range is used.   If `f_range=None`, as in your case since the filtering is performed outside the call, then `min_burst_duration` (in seconds) must be defined. If you want 50-100ms, then `min_burst_duration=0.05` or `min_burst_duration=0.1`.

Hope this helps!

**Comment by apoorva6262** [comment]
Thank you for clarifying!

With regards to `dual_thresh=(1, 2)` , can you further explain what 'normalized amplitude' is ? 
And if the burst ends when the normalized amplitude drops below `dual_thresh[0]` ?  then what is the need of "2" in `dual_thresh=(1, 2)`  ?

**Comment by ryanhammonds** [comment]
No problem!

The normalized amplitude is the [instantaneous amplitude](https://neurodsp-tools.github.io/neurodsp/auto_tutorials/timefreq/plot_InstantaneousMeasures.html#instantaneous-amplitude), divided by it's own mean (default) or median (set using the `avg_type` argument).

The 2 in `(1, 2)` defines the starts of bursts where the instantaneous amplitude > 2. This can be simplified to a single, absolute threshold with `(2, 2)`, etc - defining bursts as anywhere above 2.

**Comment by apoorva6262** [comment]
Sorry, I am still confused. If 2 in `(1 , 2)` is where the burst starts , then what does 1 in `(1 , 2)` do ? Is it where the instantaneous amplitude drops below 1 ? Because earlier you mentioned "The starts of bursts are defined where the normalized amplitude of the signal is above dual_thresh[1] " , and  I am assuming you are not referring to the 1 in this `(1 , 2)` as  dual_thresh[1]? 

And if we need to look at 3 times the median to qualify as a burst , how would you change this `(1 , 2)` argument?

**Comment by ryanhammonds** [comment]
Yeah, that's correct.

If `dual_thresh=(1, 2)`, then `dual_thresh[1] == 2`  (and  `dual_thresh[0] == 1`) as indexing starts at zero. I was using `[0]` to denote the lower threshold and `[1]` to denote the upper threshold.

If you want a single 3x median threshold, than `(3, 3)` should be appropriate. The lower threshold gives a bit more flexibility to when a bursts ends in the case of `(2, 3)`.

**Comment by apoorva6262** [comment]
ok, cool, that makes sense! thank you!
