### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by TomDonoghue** [neurodsp-tools/neurodsp#287]
On new PRs, our tests are currently failing, on the `test_phase_by_time` function (which has not changed). 

See, for example, here: https://github.com/neurodsp-tools/neurodsp/runs/4945344164?check_suite_focus=true

I don't know why this is happening. It seems to be some newer update, since 3.6 & 3.7 pass, but 3.8 & 3.9 fail. This test checks two vectors for equivalence, and based on the printout on Github actions, they are the same within the range of whats printed. I'm having trouble replicating this error - local environments with what should the same Python / numpy / scipy don't recreate the issue, and it's not obvious how to debug through Github actions. I can't any clear indication of what might have changed in Python / numpy / scipy to create this. 

@ryanhammonds - do you have any idea what might be going on here, and/or any ideas of best strategy to try and figure it out?

**Comment by ryanhammonds** [comment]
This is strange. I'm unable to replicate the issue locally either with 3.8. I also updated my scipy, numpy, pytest versions to the same that are used in GH actions and tests pass. It also looks like the operating system that GH actions uses hasn't changed, nor have the arrays since a random seed it being set in the pytest config.

I'll look into this some more and see if I can figure out what's going on.

**Comment by TomDonoghue** [comment]
Fixed by #289 - thanks Ryan!
