### ISSUE TITLE
PAC in NeuroDSP

### ISSUE THREAD

**Issue by neuropil** [neurodsp-tools/neurodsp#311]
What is the best approach for computing PAC using the neurodsp library?

Thanks!

**Comment by TomDonoghue** [comment]
We used to have some basic functions for computing PAC, but we removed them (see [here](https://github.com/neurodsp-tools/neurodsp/issues/70)) because this functionality was covered in other places (we also used to have [pactools](https://github.com/voytekresearch/pacpy), which has PAC functionality, but is no longer supported. 

I think the current recommendation would be to use [pactools](https://github.com/pactools/pactools).

**Comment by neuropil** [comment]
Thank you!!
