### ISSUE TITLE
[Question] powerlaw correlation / covariance structure

### ISSUE THREAD

**Issue by ryanhammonds** [neurodsp-tools/neurodsp#326]
I was using sim_powerlaw to try and learn about the covariance structure when a bunch of sims are stacked into rows. I noticed the covariance (and correlation) structure seemed odd. Samples at the end of the signals from sim_powerlaw are ~perfectly correlated with the beginning of the signal. Maybe I'm missing something obvious, @TomDonoghue any idea if this is expected? I reran this against other 1/f sims (e.g. random walks) and the column-wise correlation plot decayed to a min and never increased.

```python
import numpy as np
import matplotlib.pyplot as plt
from neurodsp.sim import sim_powerlaw

# Simulate powerlaws
n_sims = 1000
n_samples = 1000

X = np.zeros((n_sims, n_samples))

for i in range(n_sims):
    np.random.seed(i)
    X[i] = sim_powerlaw(1, n_samples)

np.corrcoef(X[:, 0], X[:, -1])[0][1] # returns 0.993213042285584

# Plot correlations
col_corrs = np.zeros(n_samples)

for i in range(n_samples):
    col_corrs[i] = np.corrcoef(X[:, 0], X[:, i])[0][1]

plt.plot(col_corrs)
plt.title('First Column vs Rest')
plt.ylabel("Correlation, r")
plt.xlabel('Column');
```
![ex](https://github.com/neurodsp-tools/neurodsp/assets/34786005/4e6457da-f526-4d01-84fc-81bdc19c94c9)

**Comment by TomDonoghue** [comment]
Huh, weird. 

I guess it's got to be something about scaling ('rotating') the fft values? There's not much else that goes into the powerlaw sims - as "spectrally rotated" white noise. The symmetry is making me think of positive & negative frequencies - though I don't actually have any idea if that's at all relevant here. 

Perhaps @rdgao has some insight here? 

I think it's definitely worth figuring this out a bit more - it's not an obvious property of the simulations, and might not be desired in at least some cases. It does seem very symmetric - so a brute force way to get rid of it could just to be simulate twice the signal length desired and chop in half? As far as I can tell, the first half of the signal has expected correlation structure....

**Comment by ryanhammonds** [comment]
It turns out the white noise input needs zero padding to remove the effect:

```python
def _create_powerlaw(n_samples, fs, exponent):

    # Start with white noise signal, that we will rotate, in frequency space
    sig = np.random.randn(int(n_samples))
    sig = np.pad(sig, (500, 500))

    # Create the desired exponent by spectrally rotating the time series
    sig = rotate_timeseries(sig, fs, -exponent)[500:-500]

    # z-score to normalize
    sig = zscore(sig)

    return sig
```
It has something to do with fft modes / sinsusoids wrapping around, e.g. being smooth and continuous from from the end to beginning. Zero padding breaks up the continuity. I don't know if this warrants a PR but I can make one to an padding as an option if you think it's worth it? In rare cases I could see this biasing sim results - at least it did for what I was trying.

Also I looked into positive and negative frequencies. It seems like the negative freqs are only for complex inputs. So we can use rfft, rfftfreq, irfft since the white noise input is real. This speeds up the simulations a bit.

**Comment by rdgao** [comment]
wait...what?! so the first time point across N independent simulations is 1.0 correlated with the last time point??

I think @ryanhammonds's explanation is in the right direct? The DFT assumes that it operates on a discrete periodic signal, so I guess the inverse does the same too? (Pretty sure there's a technically correct answer here, I just don't know it what it is.)

Just thinking out loud here: if you _start_ by drawing random numbers in frequency domain, by definition only frequencies that have integer number of cycles in that time can be sampled. That means, like Ryan said, the start and end of every sinusoidal component are basically identical (technically, one time-sample apart), regardless of phase shift, which would also then hold true for the sum across the sinusoids?

But that would be true for _any_ time series, since they can be decomposed the same way—a sum of integer-period sinusoids. But this seems absurd, and it also means no manipulations could break this property, since every signal is by definition that, no matter what you do. 

I can see that, for white noise, the different frequencies having equal power essentially scrambles the end points, whereas 1/f noise is dominated by just a few of the low-freq components. So the larger the exponent (or fewer components), the stronger this effect should be.

**Comment by ryanhammonds** [comment]
@rdgao Yeah, that explanation is what is being observed - there is correlation wrapping around from the beginning/end of the simulations. 

Thanks for the insight!  I don't think it holds for any time series since random walks don't have the property. But I haven't been able to make complete sense of it, other than a hack-y fix. I'll check what you mentioned about it depending on the magnitude of the exponent.
